services:
  netflix-overseerr-bridge:
    container_name: netflix-overseerr-bridge
    image: stephtanner1/netflix-overseerr-bridge:latest
    environment:
      - OVERSEERR_URL=${OVERSEERR_URL}
      - OVERSEERR_API_KEY=${OVERSEERR_API_KEY}
      - RUN_FREQUENCY=24  # Default to 24 hours if not set
      - NETFLIX_COUNTRY="United States"
      - DRY_RUN=false  # Optional: Enable dry run mode, defaults to false
      - KOMETA_ENABLED=true  # Enable Kometa YAML generation with TVDb builder
      - KOMETA_OUTPUT_DIR=/config/kometa  # Base directory for Kometa YAML files
      - KOMETA_MOVIES_DIR=/config/kometa/movies  # Specific directory for movie collections
      - KOMETA_TV_DIR=/config/kometa/tv  # Specific directory for TV collections
    volumes:
      - ./kometa:/config/kometa  # Mount directory for YAML files
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "5"
    restart: unless-stopped 